services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 4521:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: jesus
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: